server:
  port: 9000
spring:
  application:
    name: 5-API-Gateway
  cloud:
    discovery:
      enabled: true
      eureka:
        client:
           service-url:
            defaultZone: http://localhost:8761/eureka/
    zipkin:
      baseUrl: http://localhost:9411
      sender:
        type: web  
    gateway:
      routes:
      - id: Department-Service
        uri: lb://2-Department-Service
        predicates:
          - Path=/department/**
      - id: Employee-Service
        uri: lb://3-Employee-Service
        predicates:
          - Path=/employee/**