spring:
  application:
    name: 2-Department-Service
  datasource:
    url: jdbc:mysql://localhost:3306/microservice_project?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: Mysql_2112
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  cloud:
    loadbalancer:
      ribbon:
        enabled: true      
server:
  port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
management:
  tracing:
    sampling:
      probability: 1.0