spring:
  application:
    name: 1.1-Amin-Server
server:
  port: 1111
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ # Update this if Eureka is on a different server
    fetch-registry: true
    register-with-eureka: true